name: 1. Release

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 20
  NODE_ENV: production

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup node@${{ env.NODE_VERSION }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci --include dev
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true

  release:
    runs-on: ubuntu-latest
    needs: 'build-and-test'
    steps:
      - uses: actions/checkout@v4
      - name: Setup node@${{ env.NODE_VERSION }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: npm ci --include dev
      - run: npm run prepare-release
      - name: Push commit/tag
        run: |
          git push --follow-tags origin main
      - name: Set tag variable
        run: echo "RELEASE_TAG=$(git tag --points-at HEAD)" >> $GITHUB_ENV
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: ${{ env.RELEASE_TAG }}
          tag_name: ${{ env.RELEASE_TAG }}
          body_path: CHANGELOG.md
