name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  NODE_VERSION: 20
  NODE_ENV: production

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          body_path: CHANGELOG.md
